location = /project-z {
    return 308 /project-z/;
}

location ^~ /project-z/assets/ {
    alias /home/eias/services/project-z/current/assets/;
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
}

location /project-z/ {
    alias /home/eias/services/project-z/current/;
    index index.html;
    try_files $uri $uri/ /project-z/index.html;
    add_header Cache-Control "no-cache" always;
}
