"""WebSocket protocol message models for Haniel Orchestrator."""

from __future__ import annotations

import json
from enum import Enum
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class StrictMessage(BaseModel):
    """Wire message that rejects fields belonging to another protocol variant."""

    model_config = ConfigDict(extra="forbid")


class DeployStatus(str, Enum):
    """Deploy lifecycle states. Used by EventStore and Hub."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYING = "deploying"
    SUCCESS = "success"
    FAILED = "failed"


# --- Node → Server messages ---


class NodeHello(BaseModel):
    """First message sent by a node after WebSocket connect."""

    type: str = "node_hello"
    node_id: str
    token: str  # shared secret — must match OrchestratorConfig.token
    hostname: str
    os: str
    arch: str
    haniel_version: str
    services: list[dict] | None = None  # optional service list from node


class ChangeNotification(BaseModel):
    """Sent when a node detects repo changes (new commits)."""

    type: str = "change_notification"
    deploy_id: str  # deterministic: "{node_id}:{repo}:{branch}:{remote_head}"
    node_id: str
    repo: str
    branch: str
    commits: list[str]  # ["hash subject", ...] — git log --oneline format
    affected_services: list[str]
    diff_stat: str | None = None  # git diff --stat output
    detected_at: str  # ISO 8601 timestamp, generated by client
    target_head: str | None = None
    deployment_kind: Literal["legacy", "manifest"] = "legacy"
    expected_manifest_identity: str | None = None
    expected_manifest_digest: str | None = None

    @model_validator(mode="after")
    def validate_manifest_snapshot(self) -> "ChangeNotification":
        if self.deployment_kind == "manifest" and not self.expected_manifest_identity:
            raise ValueError("manifest change requires identity")
        if self.deployment_kind == "legacy" and (
            self.expected_manifest_identity is not None
            or self.expected_manifest_digest is not None
        ):
            raise ValueError("legacy change cannot carry manifest evidence")
        return self


class NodeStatus(BaseModel):
    """Heartbeat message — indicates node is alive. Optionally carries service state."""

    type: str = "node_status"
    node_id: str
    services: list[dict] | None = None


class DeployResult(StrictMessage):
    """Sent by node after a deploy completes (success or failure)."""

    type: str = "deploy_result"
    deploy_id: str
    node_id: str
    status: Literal["success", "failed"]
    error: str | None = None
    duration_ms: int | None = None
    orchestrator_attempt_id: str
    connection_generation: str


class RepoReconciliation(StrictMessage):
    """Node observation that reconciles dashboard activity with actual Git HEADs."""

    type: str = "repo_reconciliation"
    phase: Literal["observed", "attempt_started", "settled"]
    deploy_id: str
    node_id: str
    repo: str
    branch: str
    local_head: str
    remote_head: str
    orchestrator_attempt_id: str | None = None
    connection_generation: str | None = None

    @model_validator(mode="after")
    def validate_attempt_identity(self) -> "RepoReconciliation":
        if self.phase in ("attempt_started", "settled") and not self.orchestrator_attempt_id:
            raise ValueError(f"{self.phase} requires orchestrator_attempt_id")
        if self.phase == "settled" and not self.connection_generation:
            raise ValueError("settled requires connection_generation")
        return self


class DeployPlanProposal(StrictMessage):
    """Read-only node evidence returned for one generation-bound probe."""

    type: Literal["deploy_plan_proposal"] = "deploy_plan_proposal"
    mode: Literal["execute", "evidence_recovery", "fail_closed"]
    probe_id: str
    connection_generation: str
    deploy_id: str
    node_id: str
    repo: str
    branch: str
    target_head: str
    current_head: str
    journal_status: str | None = None
    journal_attempt_id: str | None = None
    linked_orchestrator_attempt_id: str | None = None
    journal_target_head: str | None = None
    original_previous_head: str | None = None
    manifest_identity: str | None = None
    manifest_digest: str | None = None
    journal_completed_at: str | None = None
    reason: str
    error: str | None = None
    fingerprint: str


class ManifestRecoveryEvidence(StrictMessage):
    """Durable local-success evidence; never an execution shortcut."""

    type: Literal["manifest_recovery_evidence"] = "manifest_recovery_evidence"
    deploy_id: str
    orchestrator_attempt_id: str
    source_orchestrator_attempt_id: str
    journal_attempt_id: str
    connection_generation: str
    node_id: str
    repo: str
    branch: str
    target_head: str
    current_head: str
    manifest_identity: str
    manifest_digest: str
    journal_status: Literal["success"]
    journal_completed_at: str
    original_previous_head: str | None = None


class DeployAttemptTerminal(StrictMessage):
    """The sole terminal kind that a node is authorized to originate."""

    type: Literal["deploy_attempt_terminal"] = "deploy_attempt_terminal"
    kind: Literal["approval_revalidation_failed"]
    deploy_id: str
    orchestrator_attempt_id: str
    connection_generation: str
    stage: Literal["approval_revalidation"] = "approval_revalidation"
    reason: str
    error: str


# --- Server → Node messages ---


class DeployApproval(StrictMessage):
    """Server instructs node to proceed with deployment."""

    type: Literal["deploy_approval"] = "deploy_approval"
    deploy_id: str
    orchestrator_attempt_id: str
    execution_mode: Literal["execute", "evidence_recovery"]
    probe_id: str | None = None
    connection_generation: str
    preflight_fingerprint: str | None = None
    approved_by: str = "dashboard"


class DeployPlanProbe(StrictMessage):
    """Read-only, generation-bound planning request; it grants no execution."""

    type: Literal["deploy_plan_probe"] = "deploy_plan_probe"
    probe_id: str
    connection_generation: str
    deploy_id: str
    node_id: str
    repo: str
    branch: str
    target_head: str
    source_orchestrator_attempt_id: str | None = None
    retry_lineage: list[str] = Field(default_factory=list)
    expected_manifest_identity: str | None = None
    expected_manifest_digest: str | None = None
    deadline_at: str
    requested_orchestrator_attempt_id: str | None = None


class AcceptedDeployAttemptAck(StrictMessage):
    type: Literal["deploy_attempt_ack"] = "deploy_attempt_ack"
    accepted: Literal[True]
    requested_orchestrator_attempt_id: str
    begun_orchestrator_attempt_id: str
    deploy_id: str
    connection_generation: str
    probe_id: str
    execution_mode: Literal["execute", "evidence_recovery"]
    preflight_fingerprint: str


class RejectedDeployAttemptAck(StrictMessage):
    type: Literal["deploy_attempt_ack"] = "deploy_attempt_ack"
    accepted: Literal[False]
    requested_orchestrator_attempt_id: str
    deploy_id: str
    connection_generation: str
    error: Literal["retry_requires_manual_approval"]


DeployAttemptAck = Annotated[
    Union[AcceptedDeployAttemptAck, RejectedDeployAttemptAck],
    Field(discriminator="accepted"),
]


class DeployReject(BaseModel):
    """Server instructs node to skip deployment."""

    type: str = "deploy_reject"
    deploy_id: str
    reason: str


class ServiceCommand(BaseModel):
    """Server instructs node to run a service/config lifecycle command."""

    type: str = "service_command"
    command_id: str  # unique ID for tracking
    service_name: str
    action: str
    payload: dict[str, Any] | None = None


# --- Node → Server messages (additional) ---


class ServiceCommandResult(BaseModel):
    """Node reports result of a service command."""

    type: str = "service_command_result"
    command_id: str
    node_id: str
    service_name: str
    action: str
    success: bool
    error: str | None = None
    result: Any = None


# Union types
OrchestratorMessage = Union[
    DeployApproval,
    DeployPlanProbe,
    AcceptedDeployAttemptAck,
    RejectedDeployAttemptAck,
    DeployReject,
    ServiceCommand,
]
NodeMessage = Union[
    NodeHello,
    ChangeNotification,
    NodeStatus,
    DeployResult,
    RepoReconciliation,
    DeployPlanProposal,
    ManifestRecoveryEvidence,
    DeployAttemptTerminal,
    ServiceCommandResult,
]

# Type dispatch map for parse_node_message
_NODE_MESSAGE_TYPES: dict[str, type[NodeMessage]] = {
    "node_hello": NodeHello,
    "change_notification": ChangeNotification,
    "node_status": NodeStatus,
    "deploy_result": DeployResult,
    "repo_reconciliation": RepoReconciliation,
    "deploy_plan_proposal": DeployPlanProposal,
    "manifest_recovery_evidence": ManifestRecoveryEvidence,
    "deploy_attempt_terminal": DeployAttemptTerminal,
    "service_command_result": ServiceCommandResult,
}


def parse_node_message(raw: str) -> NodeMessage:
    """Parse a JSON string into the appropriate NodeMessage type.

    Raises:
        ValueError: If "type" key is missing or unrecognized.
        pydantic.ValidationError: If fields fail validation.
    """
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON: {e}") from e

    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object, got {type(data).__name__}")

    msg_type = data.get("type")
    if msg_type is None:
        raise ValueError("Missing 'type' field in message")

    model_cls = _NODE_MESSAGE_TYPES.get(msg_type)
    if model_cls is None:
        raise ValueError(f"Unknown message type: {msg_type!r}")

    return model_cls.model_validate(data)
