"""WebSocket protocol message models for Haniel Orchestrator."""

from __future__ import annotations

import json
from enum import Enum
from typing import Union

from pydantic import BaseModel


class DeployStatus(str, Enum):
    """Deploy lifecycle states. Used by EventStore and Hub."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEPLOYING = "deploying"
    SUCCESS = "success"
    FAILED = "failed"


# --- Node → Server messages ---


class NodeHello(BaseModel):
    """First message sent by a node after WebSocket connect."""

    type: str = "node_hello"
    node_id: str
    token: str  # shared secret — must match OrchestratorConfig.token
    hostname: str
    os: str
    arch: str
    haniel_version: str
    services: list[dict] | None = None  # optional service list from node


class ChangeNotification(BaseModel):
    """Sent when a node detects repo changes (new commits)."""

    type: str = "change_notification"
    deploy_id: str  # deterministic: "{node_id}:{repo}:{branch}:{first_commit_hash}"
    node_id: str
    repo: str
    branch: str
    commits: list[str]  # ["hash subject", ...] — git log --oneline format
    affected_services: list[str]
    diff_stat: str | None = None  # git diff --stat output
    detected_at: str  # ISO 8601 timestamp, generated by client


class NodeStatus(BaseModel):
    """Heartbeat message — indicates node is alive. Optionally carries service state."""

    type: str = "node_status"
    node_id: str
    services: list[dict] | None = None


class DeployResult(BaseModel):
    """Sent by node after a deploy completes (success or failure)."""

    type: str = "deploy_result"
    deploy_id: str
    node_id: str
    status: str  # "success" | "failed" — server converts via DeployStatus[status.upper()]
    error: str | None = None
    duration_ms: int | None = None


# --- Server → Node messages ---


class DeployApproval(BaseModel):
    """Server instructs node to proceed with deployment."""

    type: str = "deploy_approval"
    deploy_id: str
    approved_by: str = "dashboard"


class DeployReject(BaseModel):
    """Server instructs node to skip deployment."""

    type: str = "deploy_reject"
    deploy_id: str
    reason: str


class ServiceCommand(BaseModel):
    """Server instructs node to restart/stop a service."""

    type: str = "service_command"
    command_id: str  # unique ID for tracking
    service_name: str
    action: str  # "restart" | "stop"


# --- Node → Server messages (additional) ---


class ServiceCommandResult(BaseModel):
    """Node reports result of a service command."""

    type: str = "service_command_result"
    command_id: str
    node_id: str
    service_name: str
    action: str
    success: bool
    error: str | None = None


# Union types
OrchestratorMessage = Union[DeployApproval, DeployReject, ServiceCommand]
NodeMessage = Union[
    NodeHello, ChangeNotification, NodeStatus, DeployResult, ServiceCommandResult
]

# Type dispatch map for parse_node_message
_NODE_MESSAGE_TYPES: dict[str, type[NodeMessage]] = {
    "node_hello": NodeHello,
    "change_notification": ChangeNotification,
    "node_status": NodeStatus,
    "deploy_result": DeployResult,
    "service_command_result": ServiceCommandResult,
}


def parse_node_message(raw: str) -> NodeMessage:
    """Parse a JSON string into the appropriate NodeMessage type.

    Raises:
        ValueError: If "type" key is missing or unrecognized.
        pydantic.ValidationError: If fields fail validation.
    """
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Invalid JSON: {e}") from e

    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object, got {type(data).__name__}")

    msg_type = data.get("type")
    if msg_type is None:
        raise ValueError("Missing 'type' field in message")

    model_cls = _NODE_MESSAGE_TYPES.get(msg_type)
    if model_cls is None:
        raise ValueError(f"Unknown message type: {msg_type!r}")

    return model_cls.model_validate(data)
